<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AssemblyName>DiskCleaner.Elevated</AssemblyName>
    <RootNamespace>DiskCleaner.Elevated</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiskCleaner.Core\DiskCleaner.Core.csproj" />
  </ItemGroup>

</Project>
